### ISSUE TITLE
Fix flash-after-verify in Etcher integration

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#12]

**Comment by curcuz** [comment]
@jhermsmeier we need precise instructions on how to reproduce - neither me nor @zvin were able to do so far

**Comment by jhermsmeier** [comment]
@curcuz this happened just when flashing more than one card, with auto-unmount turned off

**Comment by zvin** [comment]
I'm not sure this is specific to the `etcher-sdk` branch of etcher in etcher pro.

**Comment by zvin** [comment]
This is due to an issue in `sudo-prompt`.
PR opened on `sudo-prompt` and `etcher`.
 * https://github.com/jorangreef/sudo-prompt/pull/76
 * https://github.com/resin-io/etcher/pull/2469
Closing this.
