### ISSUE TITLE
Fix Error: Could not initialize libusb on CI

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#14]
```
Error: Could not initialize libusb. Check that your system has a usb controller.
```

See https://travis-ci.org/resin-io/etcher/jobs/403328564

**Comment by jhermsmeier** [comment]
@zvin which PR was this closed by?

**Comment by zvin** [comment]
@jhermsmeier this one https://github.com/resin-io-modules/etcher-sdk/pull/34
