### ISSUE TITLE
Fix loading of lzma-native bindings under Electron

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#15]
lzma-native attempts to load wrong binding under Electron when npm-linked

```
Error: Cannot find module 'etcher-sdk/node_modules/lzma-native/binding-v3.0.8-node-v54-darwin-x64/lzma_native.node'
```

**Comment by jviotti** [comment]
I think this is because you didn't build `etcher-sdk` against the Electron ABI, and thus when doing `npm link`, it will fail to load the native module.
