### ISSUE TITLE
Ensure that padded writes don't trash previous data on disk

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#19]
Currently when writing chunks that are non-divisible by the block size, the chunk will be zero-padded to a multiple of the block size – this could potentially wipe data unintentionally when writing smaller parts on disk individually.

While the SDK currently does not facilitate doing this, it should still be implemented properly, by reading the block in question, copy the to-be-written data over and write it back, especially for future use.

**Comment by zvin** [comment]
This can be done.
`BlockDevice` has a `read()` method. We'd need to pass the `BlockDevice` instance to BlockWriteStream instead of a file descriptor and add some logic to read the overlapping chunk.
