### ISSUE TITLE
Invalid image extensions if extension is uppercase

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#23]
![image](https://user-images.githubusercontent.com/244907/42892970-6cb5ac0e-8ab3-11e8-82b6-3a07867afbc2.png)

**Comment by celicoo** [comment]
@jhermsmeier I believe I could help with this issue. Is it only happening on Windows?

**Comment by jhermsmeier** [comment]
@celicoo thanks, feel free to open a PR :) Just to clarify; this module is a WIP, isn't being used in Etcher yet, and drastic changes might occur, so no guarantees your PR will make it in

**Comment by celicoo** [comment]
@jhermsmeier I couldn't help but notice that we are validating the supported formats [here](https://github.com/resin-io/etcher/blob/master/lib/gui/app/pages/main/controllers/image-selection.js#L72) and [here](https://github.com/resin-io/etcher/blob/master/lib/gui/app/models/store.js#L383). Is there a reason for that?

**Comment by zvin** [comment]
This should be fixed in https://github.com/resin-io/etcher/commit/6f75cd1cb1283a80bbb6dcd2d7ddb169fe7889b9

**Comment by jhermsmeier** [comment]
@zvin this shouldn't be fixed in Etcher, but the SDK – as the SDK will be consumed by other things as well, and they'd all have to take care of this trivial thing, which doesn't make much sense

**Comment by jhermsmeier** [comment]
Right, sorry – this raises the question though about how the SDK does image format detection – is that left up to the consumer?

**Comment by zvin** [comment]
There is a [`getInnerSource()`](https://github.com/resin-io-modules/etcher-sdk/blob/master/lib/source-destination/source-destination.ts#L379-L395) method on all `SourceDestination` instances that tries to detect and get the most inner source. Anything more clever than that is left up to the consumer.

**Comment by jhermsmeier** [comment]
In which I see that [getMimeTypeFromName()](https://github.com/resin-io-modules/etcher-sdk/blob/master/lib/source-destination/source-destination.ts#L349-L352) doesn't normalize the filename extension to lower case – and also doesn't actually do any MIME type detection for anything other than UDIF/DMG.

I thought we had discussed to detect the MIME by extension, unless unavailable, or not detected by that mechanism, and only then fall back to detecting by magic numbers?

**Comment by zvin** [comment]
Good catch for `getMimeTypeFromName`, I'll fix that.
This method is private and is only intended for `getInnerSource`

`getInnerSource` is implemented here as it is useful in the examples.

You can still create your source manually with something like

```typescript
const source = new GZipSource(new FileSource('image.img.gz'))
```
